### ISSUE TITLE
Add alerts/watchers as assets in packages

### ISSUE THREAD

**Issue by ChrsMark** [elastic/package-spec#484] opened 2023-02-28 04:24 UTC
At the moment we don't support alerts and watchers to be part of a package. 
At https://github.com/elastic/integrations/issues/4997 we explore how the alerting feature can enhance our Kubernetes solution. 
After having the first bunch of alerts/watchers we decided to include them in the docs' section for now with https://github.com/elastic/integrations/pull/5364.

The purpose of this issue is to propose to provide the option for alerts/watchers to be installed when installing the package. These means we should add them to their own place in the package-spec, and we should have a follow-up task in Kibana to install them when available.

**Comment by jsoriano** [comment] 2023-03-01 11:11
@ChrsMark what would be needed to store in the packages, only the watcher definition? Or would some additional setting or identifier be needed too?

**Comment by ruflin** [comment] 2023-06-01 12:12
Instead of adding support for watcher, we should instead add support for alerts and slo.

**Comment by jsoriano** [comment] 2023-08-15 19:28
Closing as duplicate of https://github.com/elastic/package-spec/issues/121, let's keep discussions about this there.

**Closed by jsoriano** 2023-08-15 19:28 UTC
Labels: discuss, Team:Ecosystem
